### ISSUE TITLE
Enable SELinux

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-installer#4]
On DO have they disabled SELinux in `/etc/selinux/config`. We should enable it and reboot in the beginning of the script.

I shouldn't give any issues for us, as we don't use any special policies.

**Comment by iainbryson** [comment]
Do you mean reboot and then continue the script, or reboot and have the user re-run the script (presumably checking for SELinux, and then proceeding?)

**Comment by dtu-compute** [comment]
Rebooting is the only way to active SELinux, so we need to reboot. Perhaps let the user type `y` to reboot or similar?

**Comment by dtu-compute** [comment]
Have just done a simple test with SELinux enabled

```
cat << EOF > /etc/yum.repos.d/docker.repo
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF

yum -y install docker-engine
mkdir /vol
docker run -ti --rm -v /vol/:/yyy alpine /bin/ash
echo abc > /yyy/test
```

and it worked.

We shouldn't enable SELinux in enote-devel, just staging and production.

So we should expect everything to just work on staging without changing anything.

**Comment by iainbryson** [comment]
As far as this ticket goes, what specific actions do you have in mind?  It seems like "turn it on and test" is the strategy.  Is that correct?

Why not enable in enote-devel?

**Comment by dtu-compute** [comment]
Yes that was my plan. Selinux tends to break programs pretty visually if there is a conflict.

We could also enable it for development but it might get more in the way then needed? It's up to you :)
________________________________

**Comment by iainbryson** [comment]
The system config should be the same everything, IMO, so we find things earlier.  The more differences with the final environment, the more risk.

**Comment by dtu-compute** [comment]
Ok. Just change it in /etc/selinux/config to enforcing and then reboot.
________________________________
